### ISSUE TITLE
Can't create DBs via nano, but can do so via command line

### ISSUE THREAD

**Issue by csuwildcat** [apache/couchdb-nano#68]
I am running the official docker image for couchdb on Windows, and it starts right up with my app, the dashboard works, and everything seems fine. The issue is that in my app nano's create db calls do not actually create new databases in the instance. When I manually curl to create via the localhost URL, new databases are created without issue.

I don't get any errors or warnings about this, but the issue feels like some sort of config or auth issue where the lib is either writing to the wrong directory or can't write to the one it is supposed to. I can't really explain it, given I can issue commands directly and it works fine.

## Expected Behavior

When I run `create()`, I should be able to create a new database and view it in the dashboard. 

## Current Behavior

Calls to `create()` report no errors, but fail to add a new db to the instance.

## Steps to Reproduce (for bugs)

I can provide the exact proj if you need it, but it is the most vanilla install possible:

Docker compose looks like this:

```
version: '2'
services:
  hub:
    build: .
    ports:
      - "3000:3000"
    environment:
      - ENVIRONMENT=dev
      - COUCHDB_URL="http://localhost:5984"
  couchdb:
    image: "couchdb"
    ports:
      - "5984:5984"
```

Nano include looks like this:

`const nano = require('nano')(appConfig.dbURL);  // dbURL is the localhost:5984`

1. Docker-compose up
2. Run node proj
3. Run simple nano `create()`
4. No errors, just doesn't create a database

## Context

Can't use couchdb/nano until this first step works.

## Your Environment

* Version used: 1.6.1
* Browser Name and version: Node 8.3.0
* Operating System and version (desktop or mobile): Windows 10 desktop
* Link to your project: https://github.com/decentralized-identity/hubs/tree/master/implementations/node
